import { InferGetServerSidePropsType, type NextPage } from "next";
import Head from "next/head";

import T3DefaultMessage from "@/components/T3DefaultMessage";
import DBTest from "@/components/DBTest";

import { CardInfo } from "@prisma/client";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps<{
  cards: CardInfo[];
}> = async () => {
  const { prisma } = require("@/utils/db");
  const cards = await prisma.cardInfo.findMany();
  return { props: { cards } };
};

const Home = ({ cards }: { cards: CardInfo[] }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-primary bg-gradient-to-b">
        {/* <T3DefaultMessage /> */}
        <DBTest cards={cards} />
      </main>
    </>
  );
};

export default Home;
