import Head from "next/head";
import { useState } from "react";
import { GetServerSideProps } from "next";

import DBTest from "@/components/DBTest";
import KBColumns from "@/components/kanban/KBColumns";

import { CardInfo } from "@prisma/client";

// icons
import { AiOutlinePlus, AiOutlineMinus } from "react-icons/ai";

export const getServerSideProps: GetServerSideProps<{
  cards: CardInfo[];
}> = async () => {
  const { prisma } = require("@/utils/db");
  const cards = await prisma.cardInfo.findMany();
  return { props: { cards } };
};

const Home = ({ cards }: { cards: CardInfo[] }) => {
  const [columnCount, setColumnCount] = useState(1);
  const addColumn = () => {
    setColumnCount(columnCount + 1);
  };
  const removeColumn = () => {
    if (columnCount <= 1) return;
    setColumnCount(columnCount - 1);
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen min-h-screen flex-col items-center justify-center bg-[#79e087]">
        {/* <DBTest cards={cards} /> */}

        <div className="fixed top-5 right-5 flex">
          <p className="mr-5 align-middle">column count: {columnCount}</p>
          <button className="icon-button rounded-l-lg" onClick={removeColumn}>
            <AiOutlineMinus />
          </button>
          <button className="icon-button rounded-r-lg" onClick={addColumn}>
            <AiOutlinePlus />
          </button>
        </div>

        <KBColumns columnCount={columnCount} cards={cards} />
      </main>
    </>
  );
};

export default Home;
